### ISSUE TITLE
3rd state, car availability

### ISSUE THREAD

**Issue by salvq** [1technophile/garage_door_sensor#1]
Hi, will it work if I add one more condition (e.g. #define GDOOR_CAR   "456743") and extend "if" condition by different figures ?

I am trying to utilize ultrasound sensor to check door open, door close and check whether car is in garage or not (if door are closed).

Thanks,

**Comment by 1technophile** [comment]
Hi,

Yes it should with some minor modifications like removing the "closeSent = true;"

**Comment by salvq** [comment]
Thanks, right I overlook that condition.
